exporters:
  otlp:
    endpoint: ""
    headers:
      Authorization: pat ${env:HASURA_DDN_PAT}
processors:
  batch: {}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
service:
  pipelines:
    traces:
      exporters:
        - otlp
      processors:
        - batch
      receivers:
        - otlp
