services:
  claimsight_postgres:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.postgres
    environment:
      CONNECTION_URI: $CLAIMSIGHT_POSTGRES_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $CLAIMSIGHT_POSTGRES_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $CLAIMSIGHT_POSTGRES_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $CLAIMSIGHT_POSTGRES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4313:8080
    networks:
      - default
      - poc-has-apal_default

networks:
  poc-has-apal_default:
    external: true
